### ISSUE TITLE
Sliders/Radio buttons do not work when no other control is visible

### ISSUE THREAD

**Issue by Brudus** [usabilla/usabilla-u4a-ios-swift-sdk#236] opened 2022-04-20 13:23 UTC
### Introduction:
We are currently facing an issue that appears to be very weird.

We have made two surveys with **5 radio button elements with 7 options each** at the beginning followed by a few free text questions. The radio buttons are displayed as sliders on iOS. The surveys appear correctly in the app. 

### The problem:
Sadly, we are not able to interact with the sliders. **Unless(!)** we scroll down until you can see another element. Then they work perfectly fine. 

### What we have tested:
We added a question with emoticons before it and the same issue was still present. We cannot interact with the sliders until we scroll to another element (the emoticons do work). But even more interesting swiping on the sliders (no matter which one) makes the selected emoji jump a little. So I assume the focus is not really on the slider then. After scrolling to the bottom to a free text question and up again the sliders do work correctly and also the emoji does not jump anymore while interacting with the sliders.

We added a checkbox above the sliders and then they worked perfectly fine right away. 

We tested one more thing: We added a checkbox after two sliders. 
On bigger devices the checkbox question was visible without scrolling. Here the sliders worked as expected.
On smaller devices the checkbox question was not visible without scrolling. Here the sliders did not work until we scrolled down and up again.

### System information:
_iOS versions used for testing_: iOS 15.4
_Usabilla version_: 6.11.0

**Edit: I was also able to reproduce this with the latest version 6.11.1**

### Attachements
1. Video of trying to use the slider (not working), then scrolling down and up again. Then it does work. 

https://user-images.githubusercontent.com/15323817/164238328-0cbdcbe2-9b43-4388-9128-7e2fa9b56641.mov

2. Video of trying to use the slider with emoticons above (not working, only the first bouncing comes from the emoticons itself, all the following are coming from interacting with one of the sliders). Again issue is fixed by scrolling down and up again.

https://user-images.githubusercontent.com/15323817/164239731-d6d8e84d-6fb8-4ad0-9bd3-4dc7105c3a5e.mov

**Comment by stodorovicc** [comment] 2022-04-28 11:17
Hi @Brudus thanks for reaching out and apologies for my delayed response.

Sorry to hear you're having issues described. I've created a bug ticket for our developers to look into this and will get back to you as soon as possible. :)

Kind Regards,
Slobodan

**Comment by stodorovicc** [comment] 2022-11-09 12:18
Hi @Brudus, we were not able to reproduce this issue. Is this issue still present for you or have you updated to our latest SDK v6.12.3? If the issue is still present, can you please share campaign id and iOS version of device where this was tested?

Thanks in advance,
Slobodan

**Comment by stodorovicc** [comment] 2023-03-27 10:14
Hi @Brudus, since we did not get any response back I will be closing this issue. Feel free to reach back to me in case the issue is still happening or if you have any other questions.

Regards,
Slobodan

**Closed by stodorovicc** 2023-03-27 10:14 UTC
Labels: bug, in progress
