### ISSUE TITLE
6.13.2 Release has broken PO and Breakpoint debugging 

### ISSUE THREAD

**Issue by PaulARamsay** [usabilla/usabilla-u4a-ios-swift-sdk#257] opened 2023-06-05 12:49 UTC
We have started having issues with our debugging tools in Xcode. When using PO we see this error after updating Usabilla 6.13.2 (was 6.13.0), also occasionally breakpoints stops runtime debugging.

```
“warning: Swift error in scratch context: error: failed to load module ‘<‘Redacted>.

Shared Swift state for <Redacted> has developed fatal errors and is being discarded.
REPL definitions and persistent names/types will be lost.

error: expression failed to parse:
unknown error“
```

We’re also seeing the following when using breakpoints

`“Shared Swift state for <Redacted> has developed fatal errors and is being discarded. REPL definitions and persistent names/types will be lost.warning: Swift error in scratch context: error: failed to load module ‘<Redacted>’”
`

Currently running XCode 14.2

**Comment by xpereta** [comment] 2023-06-06 12:45
I can confirm that we've noticed this also since version 6.13.1

**Comment by bkunat** [comment] 2023-08-24 13:32
Same here

**Comment by PaulARamsay** [comment] 2023-09-20 10:05
error: expression failed to parse:
error: virtual filesystem overlay file '/Users/sdkteam/Library/Developer/Xcode/DerivedData/Usabilla-fhpvmqrackfaibarjhlklhbxzsgu/Build/Intermediates.noindex/ArchiveIntermediates/Usabilla/IntermediateBuildFilesPath/Usabilla.build/Release-iphonesimulator/Usabilla.build/all-product-headers.yaml' not found
error: virtual filesystem overlay file '/Users/sdkteam/Library/Developer/Xcode/DerivedData/Usabilla-fhpvmqrackfaibarjhlklhbxzsgu/Build/Intermediates.noindex/ArchiveIntermediates/Usabilla/IntermediateBuildFilesPath/Usabilla.build/Release-iphonesimulator/Usabilla.build/all-product-headers.yaml' not found
error: couldn't IRGen expression. Please check the above error messages for possible root causes.

Recently re-tried with the updated SDK and seeing the above. 
Minimum OS - iOS 14,  
XCode - Version 14.2 (14C18)
Pod version - 1.12.1

**Comment by emulroy9** [comment] 2023-11-21 11:44
Thank you for your issue submission.

On December 1, we will be are closing out the issues tabs on the Usabilla GitHub repos. We will continue supporting the apps/SDKs via our Help Center and support team. Information on how to contact support will be provided in the readme sections of the repos. By consolidating our contact channels, our team can monitor and reply more efficiently.

If the issue you have reached out about persists, please send us an email at [support@usabilla.com](mailto:support@usabilla.com). Please include all details provided here in your email, along with any other details that may be helpful.

-GetFeedback Digital Team

**Closed by emulroy9** 2023-11-21 11:44 UTC
Labels: bug, in progress
