### ISSUE TITLE
Usabilla SDK 6.1.0 triggering console warnings on Xcode 10.2 / swift 5 

### ISSUE THREAD

**Issue by Nonnus** [usabilla/usabilla-u4a-ios-swift-sdk#131] opened 2019-04-04 18:02 UTC
After updating Usabilla to latest version (6.1.0), every time i start my app I see console warnings regarding Usabilla

```
"Usabilla: SDK finished initializing"
*** /Users/teamsdk/.jenkins/workspace/sdk_swift-sdk_master-UDM67NCBBOBYKLFJF34FF5NVHPULDTM3QQPCZXIURE2F3I77F26Q/Usabilla/EventEngine/Leaves/Event.swift:15:5: implicit Objective-C entrypoint -[Usabilla.Event initWithName:] is deprecated and will be removed in Swift 4; add explicit '@objc' to the declaration to emit the Objective-C entrypoint in Swift 4 and suppress this message
Current stack trace:
0    libswiftCore.dylib                 0x000000011792dcf0 swift::warningv(unsigned int, char const*, __va_list_tag*) + 115
1    libswiftCore.dylib                 0x000000011792dd80 swift::warning(unsigned int, char const*, ...) + 123
2    libswiftCore.dylib                 0x000000011797c310 swift_objc_swift3ImplicitObjCEntrypoint + 596
3    Usabilla                           0x000000011158d550 @objc Event.init(name:) + 57
4    Usabilla                           0x000000011158d680 Event.init(coder:) + 238
5    Usabilla                           0x000000011158d7d0 @objc Event.init(coder:) + 35
6    Foundation                         0x0000000111eb3f44 _decodeObjectBinary + 2421
7    Foundation                         0x0000000111eb2dec _decodeObject + 246
8    Foundation                         0x0000000111eb2d11 -[NSKeyedUnarchiver decodeObjectForKey:] + 205
9    Usabilla                           0x00000001114e0760 LeafEvent.init(coder:) + 62
10   Usabilla                           0x00000001114e08b0 @objc LeafEvent.init(coder:) + 35
11   Foundation                         0x0000000111eb3f44 _decodeObjectBinary + 2421
12   Foundation                         0x0000000111eb2dec _decodeObject + 246
13   Foundation                         0x0000000111eb2d11 -[NSKeyedUnarchiver decodeObjectForKey:] + 205
14   Usabilla                           0x00000001115734a0 Decorator.init(coder:) + 57
15   Usabilla                           0x00000001115589d0 specialized RepetitionDecorator.init(coder:) + 168
16   Usabilla                           0x0000000111558760 @objc RepetitionDecorator.init(coder:) + 35
17   Foundation                         0x0000000111eb3f44 _decodeObjectBinary + 2421
18   Foundation                         0x0000000111eb2dec _decodeObject + 246
19   Foundation                         0x0000000111eb2d11 -[NSKeyedUnarchiver decodeObjectForKey:] + 205
20   Usabilla                           0x00000001115734a0 Decorator.init(coder:) + 57
21   Usabilla                           0x0000000111539b00 specialized PercentageDecorator.init(coder:) + 178
22   Usabilla                           0x0000000111539880 @objc PercentageDecorator.init(coder:) + 35
23   Foundation                         0x0000000111eb3f44 _decodeObjectBinary + 2421
24   Foundation                         0x0000000111eb2dec _decodeObject + 246
25   Foundation                         0x0000000111eb2d11 -[NSKeyedUnarchiver decodeObjectForKey:] + 205
26   Usabilla                           0x000000011159e430 TargetingOptionsModel.init(coder:) + 340
27   Usabilla                           0x000000011159e8c0 @objc TargetingOptionsModel.init(coder:) + 35
28   Foundation                         0x0000000111eb3f44 _decodeObjectBinary + 2421
29   Foundation                         0x0000000111eb2dec _decodeObject + 246
30   Foundation                         0x0000000111eb2d11 -[NSKeyedUnarchiver decodeObjectForKey:] + 205
31   Usabilla                           0x00000001115a5500 CampaignModel.init(coder:) + 1475
32   Usabilla                           0x00000001115a6000 @objc CampaignModel.init(coder:) + 35
33   Foundation                         0x0000000111eb3f44 _decodeObjectBinary + 2421
34   Foundation                         0x0000000111eb2dec _decodeObject + 246
35   Foundation                         0x0000000111eb2d11 -[NSKeyedUnarchiver decodeObjectForKey:] + 205
36   Foundation                         0x0000000111e5d81b -[NSCoder(Exceptions) __tryDecodeObjectForKey:error:decodeBlock:] + 65
37   Foundation                         0x0000000111e5cbb5 -[NSCoder decodeTopLevelObjectForKey:error:] + 74
38   Foundation                         0x0000000111eb2182 +[NSKeyedUnarchiver unarchiveTopLevelObjectWithData:error:] + 107
39   libswiftFoundation.dylib           0x0000000117e6d7f0 static NSKeyedUnarchiver.unarchiveTopLevelObjectWithData(_:) + 188
40   Usabilla                           0x0000000111570ca0 specialized closure #1 in UBFileStorageDAO.read(id:) + 257
41   Usabilla                           0x00000001115721a0 partial apply for specialized  + 43
42   Usabilla                           0x0000000111572180 partial apply for specialized  + 30
43   Usabilla                           0x0000000111571540 partial apply for thunk for @callee_guaranteed () -> () + 17
44   Usabilla                           0x0000000111572bd0 thunk for @callee_guaranteed () -> ()partial apply + 9
45   Usabilla                           0x00000001115704c0 thunk for @escaping @callee_guaranteed () -> () + 14
46   libdispatch.dylib                  0x0000000118bf8dad _dispatch_client_callout + 8
47   libdispatch.dylib                  0x0000000118c06c84 _dispatch_lane_barrier_sync_invoke_and_complete + 132
48   Usabilla                           0x000000011156e5a0 specialized UBFileStorageDAO.readAll() + 1512
49   Usabilla                           0x000000011153d620 closure #1 in closure #1 in UBCampaignStore.getCampaigns(withAppID:) + 704
50   Usabilla                           0x0000000111540000 partial apply for closure #1 in closure #1 in UBCampaignStore.getCampaigns(withAppID:) + 21
51   Usabilla                           0x0000000111540020 partial apply for thunk for @escaping @callee_guaranteed (@guaranteed Cachable<[CampaignModel]>) -> () + 20
52   Usabilla                           0x0000000111538430 specialized closure #1 in Promise.init(resolvers:) + 100
53   Usabilla                           0x000000011153ff00 partial apply for specialized  + 15
54   Usabilla                           0x000000011153ff30 partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed Cachable<[CampaignModel]>) -> () + 37
55   Usabilla                           0x000000011153f190 closure #2 in closure #1 in closure #1 in UBCampaignStore.getCampaignsFromService(withAppID:) + 173
56   Usabilla                           0x0000000111540db0 partial apply for closure #2 in closure #1 in closure #1 in UBCampaignStore.getCampaignsFromService(withAppID:) + 21
57   Usabilla                           0x0000000111540dd0 partial apply for thunk for @escaping @callee_guaranteed (@guaranteed [TargetingOptionsModel]) -> () + 20
58   Usabilla                           0x00000001115383b0 specialized closure #1 in Promise.init(resolvers:) + 100
59   Usabilla                           0x0000000111538dc0 specialized closure #1 in Promise.init(resolvers:) + 9
60   Usabilla                           0x00000001114f2870 partial apply for specialized  + 15
61   Usabilla                           0x00000001114f28a0 partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed [TargetingOptionsModel]) -> () + 37
62   Usabilla                           0x00000001114f0fa0 closure #1 in closure #1 in CampaignService.getTargetings(withIDs:) + 1286
63   Usabilla                           0x00000001114f2b30 partial apply for closure #1 in closure #1 in CampaignService.incrementCampaignViews(forCampaignID:viewCount:) + 25
64   Usabilla                           0x00000001114f2910 partial apply for closure #1 in closure #1 in CampaignService.getTargetings(withIDs:) + 16
65   Usabilla                           0x00000001114dcaa0 closure #1 in closure #1 in static HTTPClient.request(request:responseQueue:allowNilData:completion:) + 4174
66   Usabilla                           0x00000001114deb80 partial apply for closure #1 in closure #1 in static HTTPClient.request(request:responseQueue:allowNilData:completion:) + 58
67   Usabilla                           0x00000001114ddd50 thunk for @escaping @callee_guaranteed () -> () + 32
68   libdispatch.dylib                  0x0000000118bf7d73 _dispatch_call_block_and_release + 12
69   libdispatch.dylib                  0x0000000118bf8dad _dispatch_client_callout + 8
70   libdispatch.dylib                  0x0000000118c05a7c _dispatch_main_queue_callback_4CF + 1540
71   CoreFoundation                     0x000000011594f8a0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
72   CoreFoundation                     0x0000000115949650 __CFRunLoopRun + 2310
73   CoreFoundation                     0x0000000115949090 CFRunLoopRunSpecific + 626
74   GraphicsServices                   0x000000011e4252bd GSEventRunModal + 65
75   UIKitCore                          0x000000011b2e6b16 UIApplicationMain + 140
76   HelloFresh                         0x00000001096ab940 main + 246
77   libdyld.dylib                      0x0000000118c6d540 start + 1
```

**Comment by torkvell** [comment] 2019-04-08 06:28
Hi @Nonnus ,

Thanks for letting us know about this. This is a deprecated method warning. We will have a look at the possibility of using a newer method. 

Let me know if there is anything else I can help out with.

**Comment by torkvell** [comment] 2019-04-08 06:32
Closed as an exact duplicate of https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/132

**Closed by torkvell** 2019-04-08 06:32 UTC
