### ISSUE TITLE
Turning off Photo permissions causes crash

### ISSUE THREAD

**Issue by quinnthomson** [usabilla/usabilla-u4a-ios-swift-sdk#56] opened 2017-08-02 05:17 UTC
If the photo permissions are turned off while the photo gallery is showing, the app crashes.

To recreate:
1. Launch a feedback form
2. Allow photo gallery access
3. While the photo gallery is showing, go to device settings
4. Turn off photos permission in device settings
5. Go back to the app
6. Crash 😞 

I tried this out in a couple other apps and they're able to handle this permissions removal gracefully without a crash. Is there anything that I can do to prevent this?

**Comment by grimabe** [comment] 2017-08-02 07:44
Hi @quinnthomson,

It is unfortunate you are experiencing a crash with the SDK.
Could you please provide us with the following information where the issue is happening: 

- Usabilla SDK version 
- iOS version
- Device model
- Physical device or simulator or both

Thank you

**Comment by quinnthomson** [comment] 2017-08-02 16:39
Usabilla SDK version 3.6
Confirmed in:
iOS 9.3.5 on physical device iphone 6+
iOS 10.3.2 on physical device iphone 6
iOS 11beta3 on physical device ipad air

Let me know if there's anything else that I can try. 😄

**Comment by Goseong** [comment] 2017-09-29 09:53
Hi @quinnthomson,

Thank you for your feedback. 

When we run this scenario it will only close the SDK, it does not crash. 

I am wondering why a user gives your app permission to access the photo library and while providing their feedback inside the form, would leave the app and go into the iOS system settings, revoke the permission, and then try to attach a photo from the library. As described in your scenario below:

> 1. Launch a feedback form
> 2. Allow photo gallery access
> 3. While the photo gallery is showing, go to device settings
> 4. Turn off photos permission in device settings
> 5. Go back to the app
> 6. Crash

I am closing this ticket. Please let me know if there is a valuable reason for supporting the scenario you describe.

Regards,

Tjerk

**Closed by Goseong** 2017-09-29 09:53 UTC
