### ISSUE TITLE
LLDB issues

### ISSUE THREAD

**Issue by pmwiseman** [usabilla/usabilla-u4a-ios-swift-sdk#212] opened 2020-10-22 22:26 UTC
We just implemented Usabilla version 6.5.0 in our application, it seems that because of this we cannot use LLDB properly. When trying to execute a command we are presented with the following error:

```
error: virtual filesystem overlay file '/Users/sdkteam/Documents/Buildbot/builds/ej687hwA/0/usabilla/dev/mobile/ios/usabilla-u4a-ios-swift/build/Build/Intermediates.noindex/Usabilla.build/Release-iphonesimulator/Usabilla.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

It looks like downgrading to 6.4.7 fixes the issue, but in the release notes for 6.5.0 it's noted that a crash was fixed.  So I don't believe downgrading is a good solution to this issue. How can we solve this? Our Xcode version is `12.0.1` and I used Cocoapods to setup the SDK. Let me know if there is any other information you require. Thanks.

**Comment by eduakaszas** [comment] 2020-10-23 15:04
Hi @pmwiseman , 

Thank you for your message & all the information. 

Could you please try cleaning derived data and module cache to see if that resolves the issue? Please let us know how it goes. 

Kind regards, 
Édua

**Comment by pmwiseman** [comment] 2020-10-27 00:46
Hi Édua,

Thanks for the response. We tried those suggestions and they didn't work.  The error says something is missing from `sdkteam/Documents/Buildbot/builds`, which isn't our path.

Thanks,

Patrick

**Comment by dan11218** [comment] 2020-10-29 17:26
Hi @pmwiseman thanks for getting back to us! I am following up with our developers to check for other suggestions you can try to get past your error. Thanks for patience on this!

**Comment by jeroenleenarts** [comment] 2020-11-10 14:42
Any word yet on this?

**Comment by ctreffs** [comment] 2020-11-25 13:57
We face the same issue using Cocoapod `Usabilla 6.6.0` with `Xcode Version 12.2 (12B45b)`.

```
Couldn't parse conditional expression:
error: virtual filesystem overlay file '/Users/sdkteam/Documents/GitHub/usabilla-u4a-ios-swift/build/Build/Intermediates.noindex/Usabilla.build/Release-iphonesimulator/Usabilla.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

Cleaning derived data/clean building does **not** solve the problem for us.

**Comment by eduakaszas** [comment] 2020-11-26 09:48
Hi both, 

Thank you for your message. 

Our developers are investigating this issue. 

We'll get back to you as soon as possible with more information. Apologies for the delay. 

Kind regards, 
Édua

**Comment by BriToGolf** [comment] 2020-12-01 07:58
Hi Édua,

It has been a while ago, but is there any news on this issue?

Kind Regards,

Ton.

**Comment by eduakaszas** [comment] 2020-12-01 09:08
Hi @BriToGolf , 

Thank you for your patience. 

A workaround for this issue is to add a (dummy) Objective-C file and a bridging header to the project.

Currently there is a hard requirement that the version of the Swift compiler that builds source files and the version of lldb used to debug must come from the same toolchain. The underlying issue here is because lldb is not able to build a Swift context for expression evaluation (including variable inspection) without importing the full tree of module dependencies.

Let me know if you have any questions. 

Kind regards, 
Édua

**Comment by jeroenleenarts** [comment] 2020-12-01 09:43
@eduakaszas We have a main app target with a bridging header. And we are still getting this error. So the workaround does not apply in general. Do note, our poject is a built up out of 20 dynamic frameworks, 1 app target, 5 SPM targets and Firebase/Usabilla as CocoaPods.

It would be a huge burden for us to add a bridging header to each framework. Especially because it completely destroys our compile times.

I can suggest an easy fix for this. Opensource the client side SDK. Then you will have no trouble at all in having the compiler versions match up. :)

**Comment by adriangabardo** [comment] 2020-12-02 00:13
Would like to add to this issue as my team has also updated Usabilla to version `6.6.0` and it has broken lldb debugging on our project. Can't sort out any workarounds for it at the moment and just like Jeroen, I would say a bridging header is not a viable solution. It's quite a hinder on developing now with debugging not working, hoping this gets fixed soon.

**Comment by eduakaszas** [comment] 2020-12-02 07:33
Hi all, 

Thank you for all the additional information and I'm sorry you're encountering these issues. 

We're releasing a fix for this issue next week with the new SDK release. 

During our testing, we didn't experience these LLDB issues on SDK v6.6.0 and xCode build 12.0 & 12.2. Therefore, as a workaround (until next week's release) we'd recommend upgrading the SDK to v6.6.0. 

In case the issue still persists on v6.6.0, then we could potentially do a path release if we have enough information. @adriangabardo could you please double-check that you're indeed running v6.6.0 and let us know what xCode version and dependency manager (CocoaPods, Carthage, SwiftPM) you're using?

Looking forward to hearing from you. 

Kin regards, 
Édua

**Comment by adriangabardo** [comment] 2020-12-02 22:00
@eduakaszas confirming I am on v6.6.0. Cartfile.resolved: `binary "https://raw.githubusercontent.com/usabilla/usabilla-u4a-ios-swift-sdk/master/Usabilla.json" "6.6.0"`
Using Carthage for package management, and on Xcode 12.3 beta (latest at this point in time).

**Comment by eduakaszas** [comment] 2020-12-07 07:08
Hi @adriangabardo,

Thank you for the additional information. 

Could you please try clearing Carthage cache on your end and let us know whether the issue still persists afterwards?

Looking forward to hearing from you. 

Kind regards, 
Édua

**Comment by jeroenleenarts** [comment] 2021-01-18 18:38
Version 6.6.0 still caused this issue for us.

**Comment by eduakaszas** [comment] 2021-01-20 10:59
Hi @jeroenleenarts ,

Sorry to hear you're still running into this issue. 

Are you using M1 machines, perhaps?

Looking forward to hearing from you. 

Kind regards, 
Édua

**Comment by jeroenleenarts** [comment] 2021-01-22 09:07
@eduakaszas Both. Main development machines are still Intel. But we want to be ready to make the switch. Also running an iOS iPad app on an M1 Mac is something we want to look into. If that works, maybe even Catalyst.

**Comment by eduakaszas** [comment] 2021-02-03 09:10
Hi @jeroenleenarts , 

Thank you for your response. 

Are you using any swift packages? Additionally, would it be possible for you to update to the latest version of the SDK (v6.6.1)? Our developers have been running tests with that version and could not reproduce the issue. 

Looking forward to hearing from you. 

Kind regards, 
Édua

**Comment by adriangabardo** [comment] 2021-02-04 21:57
Haven't updated to `v6.6.1` but our team went back to `v6.5.0`, confirming I am not having LLDB issues on that version anymore. Seems to have been introduced at `v6.6.0`

**Comment by eduakaszas** [comment] 2021-05-04 08:31
Hi @adriangabardo , @jeroenleenarts, 

Hope you're doing well. 

This issue has been fixed with the latest release. We'll close this ticket for now, however, feel free to reach out again in case the issue still persists. 

Kind regards, 
Édua

**Closed by eduakaszas** 2021-05-04 08:31 UTC
Labels: bug

**Comment by adriangabardo** [comment] 2021-05-04 23:30
I am no longer in the team that was using your product, but I am sure they will appreciate the fix. Thank you for the help! Cheers.

**Comment by xanderwernecke** [comment] 2022-06-24 08:21
Hi @baderbenzribia , 

Our developers have asked if you can please update to v6.12.0 and let us know if you are still experiencing the same issue.

Thanks again,
Xander

**Comment by baderbenzribia** [comment] 2022-06-24 13:39
Hi,

It is also happening with v6.12.0
I'm getting this error
```
error: virtual filesystem overlay file '/Users/sdkteam/Library/Developer/Xcode/DerivedData/Usabilla-fhpvmqrackfaibarjhlklhbxzsgu/Build/Intermediates.noindex/ArchiveIntermediates/Usabilla/IntermediateBuildFilesPath/Usabilla.build/Release-iphonesimulator/Usabilla.build/all-product-headers.yaml' not found
error: virtual filesystem overlay file '/Users/sdkteam/Library/Developer/Xcode/DerivedData/Usabilla-fhpvmqrackfaibarjhlklhbxzsgu/Build/Intermediates.noindex/ArchiveIntermediates/Usabilla/IntermediateBuildFilesPath/Usabilla.build/Release-iphonesimulator/Usabilla.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

Thanks,
Bader

**Comment by xanderwernecke** [comment] 2022-06-24 14:32
Hi @baderbenzribia , 

What are you using as a dependency manager (carthage / cocoapods or SPM?) 

Thanks again

**Comment by baderbenzribia** [comment] 2022-06-28 10:31
Hello again,

We are using cocoapods with Xcode 13.2.1 on M1.
I have just updated my Xcode, and seems to be working fine with Xcode 13.4.1.

Thanks,
Bader
