### ISSUE TITLE
Usabilla overrides appearance text attributes for UIBarButtonItems

### ISSUE THREAD

**Issue by edwinveger** [usabilla/usabilla-u4a-ios-swift-sdk#75] opened 2017-11-07 14:59 UTC
Upon app startup, we have the following code:

```swift
let attributes = [NSAttributedStringKey.foregroundColor: UIColor.orange]
UIBarButtonItem.appearance().setTitleTextAttributes(attributes, for: .normal)

```

This adds an orange color to the navigation bar buttons. 
However, if I trigger Usabilla (either from an event-triggered campaign or user initiated form) all our navigation bar buttons turn white! This is a rather substantial problem, because the navigation bar background is also white, which renders the buttons invisible for our users.

I expect the specific color white is related to our campaign configuration. Nevertheless triggering a form should not have any impact on the rest of app appearance. 

We're using Xcode 9.1 and Usabilla v4.0.1 installed through Carthage.

![img_0046](https://user-images.githubusercontent.com/11927376/32500026-73b34800-c3d4-11e7-95ba-a91960583b10.png)

![img_0047](https://user-images.githubusercontent.com/11927376/32500039-7a16c5d2-c3d4-11e7-9f6a-7087b4c046cc.png)

**Comment by hackiftekhar** [comment] 2017-11-10 16:13
I’m getting same issue, it’s a problem with 4.0.1. The 4.0.0 is safe.

Being an open source library maintainer, I can say it’s bad practice to change appearance proxy in third party library/framework. Usabilla should come with some other tweaks and remove appearance proxy code.

**Comment by Goseong** [comment] 2017-11-16 15:48
@edwinveger @hackiftekhar we are planning to release a new version of the SDK with a fix next week.

**Comment by hackiftekhar** [comment] 2017-11-18 06:49
Thanks @Goseong

**Comment by federicocappelli-je** [comment] 2017-11-20 12:31
A big problem for us too, you are changing the navigation bar appearance for the entire app! waiting for a fix.

**Comment by edwinveger** [comment] 2017-11-27 07:53
It seems a new version with a fix has been released three days ago.

**Comment by grimabe** [comment] 2017-11-27 07:55
@hackiftekhar @federicocappelli-je 
@edwinveger is right we released a new version Friday

Please have a look at the [tags](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/tags)  or releases to see which one you need to use based on your Xcode version.

I am closing this issue.

**Closed by grimabe** 2017-11-27 07:55 UTC

**Comment by federicocappelli-je** [comment] 2017-11-27 10:45
@grimabe I've noticed that the navigation bar appearance set globally is still overwritten in the Usabilla feedback page, is this the intended behaviour? IMO Usabilla should maintain the global appearance, at least in the navigation bar.

**Comment by grimabe** [comment] 2017-11-27 11:01
@federicocappelli-je I think this belongs to another topic.
Indeed, the form is entirely customizable and the navigation bar is part of it. The design and color definition has been thought in a way to get consistency across all elements in the view.
If you want the form navigation bar to look the same as your app you can configure the font properties of the theme with `Usabilla.theme.fonts` and you can customize the colors on [Usabilla Web App.](http://app.usabilla.com).

Please open a new issue in case you have other concerns (as this one is about bar button item colors).

Thank you!
