### ISSUE TITLE
Constraint warnings in feedback form, form unresponsive

### ISSUE THREAD

**Issue by idrougge** [usabilla/usabilla-u4a-ios-swift-sdk#261] opened 2023-07-06 13:21 UTC
SDK version: 6.13.2
Device: iOS Simulator (iPhone SE  (1st generation) – iOS 15.5

Steps to reproduce:
1. Call `Usabilla.loadFeedbackForm(<#form ID#>)`
2. In `formDidLoad(form: UINavigationController)` call `show(form, sender: self)`.
3. Scroll around on presented form. The view will fail to scroll after a while.

The Xcode debugger reports:
```
2023-07-06 15:19:44.136738+0200 MyApp[47929:25072221] [Assert] button text attributes only respected for UIControlStateNormal, UIControlStateHighlighted, UIControlStateDisabled and UIControlStateFocused. state = 4 is interpreted as UIControlStateHighlighted.
2023-07-06 15:19:44.137086+0200 MyApp[47929:25072221] [Assert] button text attributes only respected for UIControlStateNormal, UIControlStateHighlighted, UIControlStateDisabled and UIControlStateFocused. state = 4 is interpreted as UIControlStateHighlighted.
2023-07-06 15:19:44.137299+0200 MyApp[47929:25072221] [Assert] button text attributes only respected for UIControlStateNormal, UIControlStateHighlighted, UIControlStateDisabled and UIControlStateFocused. state = 4 is interpreted as UIControlStateHighlighted.
2023-07-06 15:19:44.154646+0200 MyApp[47929:25072221] [Assert] button text attributes only respected for UIControlStateNormal, UIControlStateHighlighted, UIControlStateDisabled and UIControlStateFocused. state = 4 is interpreted as UIControlStateHighlighted.
2023-07-06 15:19:44.154848+0200 MyApp[47929:25072221] [Assert] button text attributes only respected for UIControlStateNormal, UIControlStateHighlighted, UIControlStateDisabled and UIControlStateFocused. state = 4 is interpreted as UIControlStateHighlighted.
2023-07-06 15:19:44.155064+0200 MyApp[47929:25072221] [Assert] button text attributes only respected for UIControlStateNormal, UIControlStateHighlighted, UIControlStateDisabled and UIControlStateFocused. state = 4 is interpreted as UIControlStateHighlighted.
2023-07-06 15:19:44.164471+0200 MyApp[47929:25072221] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002640cd0 UIView:0x7fa4e3d98990.left == UIView:0x7fa4e3d13db0.left   (active)>",
    "<NSLayoutConstraint:0x600002641360 UIView:0x7fa4e3d98990.right == UIView:0x7fa4e3d13db0.right   (active)>",
    "<NSLayoutConstraint:0x6000026bd8b0 H:|-(16)-[UILabel:0x7fa4e3fb8a30](LTR)   (active, names: '|':UIView:0x7fa4e3d98990 )>",
    "<NSLayoutConstraint:0x6000026bca50 UILabel:0x7fa4e3fb8a30.right == UIView:0x7fa4e3d98990.right - 16   (active)>",
    "<NSLayoutConstraint:0x6000026bf930 'UIView-Encapsulated-Layout-Width' UIView:0x7fa4e3d13db0.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000026bca50 UILabel:0x7fa4e3fb8a30.right == UIView:0x7fa4e3d98990.right - 16   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2023-07-06 15:19:44.198099+0200 MyApp[47929:25072221] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x60000260eee0 _TtCC8Usabilla10NPSControl8NPSLabel:0x7fa4e2fd1170.top == UIView:0x7fa4e2f49620.top - 4   (active)>",
    "<NSLayoutConstraint:0x60000261ef30 V:|-(0)-[UIStackView:0x7fa4e2fe1740]   (active, names: '|':UIView:0x7fa4e2f49620 )>",
    "<NSLayoutConstraint:0x6000025e2080 'UISV-canvas-connection' UILayoutGuide:0x600003cfd6c0'UIViewLayoutMarginsGuide'.top == _TtCC8Usabilla10NPSControl8NPSLabel:0x7fa4e2fd1170.top   (active)>",
    "<NSLayoutConstraint:0x6000025e2260 'UIView-topMargin-guide-constraint' V:|-(0)-[UILayoutGuide:0x600003cfd6c0'UIViewLayoutMarginsGuide']   (active, names: '|':UIStackView:0x7fa4e2fe1740 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000025e2080 'UISV-canvas-connection' UILayoutGuide:0x600003cfd6c0'UIViewLayoutMarginsGuide'.top == _TtCC8Usabilla10NPSControl8NPSLabel:0x7fa4e2fd1170.top   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```

**Comment by lennardtastic** [comment] 2023-09-07 13:14
Duplicate of https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/248 . Closing this, please refer to the other issue for updates.

**Closed by lennardtastic** 2023-09-07 13:14 UTC

**Comment by idrougge** [comment] 2023-09-07 13:29
@lennardtastic There haven't been updates since a year on #248. Consider fixing issues instead of closing them.
