### ISSUE TITLE
"submit" button text lowercase

### ISSUE THREAD

**Issue by federicocappelli** [usabilla/usabilla-u4a-ios-swift-sdk#47] opened 2017-05-23 13:51 UTC
The "submit" button is lowercase, is that expected?

![simulator screen shot 23 may 2017 13 07 22](https://cloud.githubusercontent.com/assets/1489236/26357396/0e630490-3fc7-11e7-8c02-badae4644f4b.png)

Thanks

**Comment by grimabe** [comment] 2017-05-23 14:07
Hi @federicocappelli 

Could you provide the version of the SDK you are using?
Could you also check the value of the submit button field in the advanced panel of the form you are using (on the setup page of the form)?

Also, this view looks like the default form: are you passing a correct form id to the SDK ? is the device connected to the internet?

Thank you

**Comment by federicocappelli** [comment] 2017-05-23 15:01
Hi @grimabe 
SDK version = 3.4.3
Value = "submit" <- yep, good point, I've just updated the string with "Submit" but the form in the app is still lowercase (app restarted and killed) Do you use some sort of caching?

**Comment by grimabe** [comment] 2017-05-23 15:06
HI @federicocappelli 

Yes, there is a caching feature, but if your device is connected to the internet it should fetch the form again. 

Could you make the following check: 
- [ ] the form id you are using in your code is the same as the one you created in Usabilla website.
- [ ] your device is connected to the internet and has no proxy.

Could you also write an email to support@usabilla.com and within this email you add the link to this issue as well as the form id you are using ?

Thank you

**Comment by federicocappelli** [comment] 2017-05-23 15:16
@grimabe 
- Form id: 5798b2d2d3ee0ddfd04ac036 , double checked.
- iPhone with working connection, all the other apps are working correctly.
- Email to Support sent.

Thanks

**Comment by grimabe** [comment] 2017-05-23 15:17
Thanks
I removed the form id from your answer.
We will look into it and come back to you.

**Comment by grimabe** [comment] 2017-05-23 15:55
After some investigation, I did not achieve to reproduce this using the provided form id.
The SDK is definitely providing you with the default form.

Could you perform the following steps:
 
- [ ] provide us with the iOS version, device model, simulator it is happening
- [ ] share the code you are using to use our SDK
- [ ] remove the app and install it again to see if it could be a caching problem

Thank you

**Comment by federicocappelli** [comment] 2017-05-23 16:23
- Simulator and real device: iPhone 7, iOS 10.3
- Here the code: https://pastebin.com/4aWNM9vB
- App removed and reinstalled, no changes in the button title. 

Note: I'm not sure if my app uses any NSURL/NSURLSession global caching, do you clean explicitly your cache?

**Comment by federicocappelli** [comment] 2017-06-10 20:48
Updates from a mail thread:

> Investigating the problem I think I've discovered what the real issue is.
> If the phone is connected to our WIFI, both your preview app and our App are returning the default form, if it is connected to the 3G network everything works as expected.
> Our IT department inspects the network traffic if the host "reputation" is low, and in order to do that they act as "man in the middle" and replaces the original TSL certificate with a Just Eat certificate, this probably make your SDK HTTPS network calls to fail, not being able to validate the certificate and forces the SDK to present the default form.
> 
> From a technical point of view here I see 2 problems:
> 
> - The Usabilla SDK fails too silently, not allowing us to detect and log errors. I would expect an NSError in your delegate call, something like:
> ` public func formFailedLoading(_ backupForm: UINavigationController, error: NSError?​) `
> 
> - The fact that the Usabilla SDK relies on the HTTPS certificate sounds "dangerous", I'm expecting that a lot of our customers are connected to business LAN with heavy traffic inspection and control and I would like to assure the correct behaviour in any possible network condition/configuration.

**Comment by grimabe** [comment] 2017-06-12 11:37
Hi @federicocappelli 

I am closing this issue as it is related to your network environment replacing the TLS certificates and not to our SDK.

However, as you mentioned, the SDK should tell you when the form has been successfully loaded or not.
The **formLoadedCorrectly** delegate method should only be called when the form has been successfully fetched from the internet or from the cache.
The **formFailedLoading** delegate method should be called when it was not possible to fetch the form and therefore provide you with the default form but it appears that this method is not working properly anymore. We will look into it, make a new release and let you know.

Thanks
Benjamin

**Closed by grimabe** 2017-06-12 11:37 UTC
